INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (101,'Engineering','United States','California','San Diego',1808);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (102,'Marketing','United States','Kentucky','Lexington',1701);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (103,'Business Development','United States','Virginia','Arlington',1263);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (104,'Support','United States','District of Columbia','Washington',1637);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (105,'Sales','United States','Florida','Miami',1108);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (106,'Research and Development','United States','Ohio','Dayton',1187);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (107,'Sales','United States','Indiana','Indianapolis',1333);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (108,'Training','United States','Colorado','Littleton',1855);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (109,'Sales','United States','Montana','Billings',1149);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (110,'Services','United States','Alabama','Birmingham',1677);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (111,'Business Development','United States','Louisiana','Baton Rouge',1040);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (112,'Marketing','United States','Nebraska','Omaha',1344);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (113,'Research and Development','United States','Virginia','Alexandria',1670);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (114,'Services','United States','Michigan','Detroit',1398);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (116,'Sales','United States','New York','Syracuse',1366);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (117,'Training','United States','Pennsylvania','Philadelphia',1820);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (118,'Services','United States','New York','Albany',1507);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (119,'Sales','United States','Florida','Pensacola',1824);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (115,'Sales','United States','Virginia','Arlington',1262);
INSERT INTO my_company.department_info (department_id,department_name,country,state,city,manager_id) VALUES (120,'Support','United States','Colorado','Aurora',1881);